# Generated by Django 2.1a1 on 2019-03-31 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_assignee',
        ),
        migrations.AddField(
            model_name='task',
            name='task_assignee',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
